name: bnf
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - atk-1.0=2.38.0
  - bedtools=2.31.1
  - boost-cpp=1.82.0
  - bowtie2=2.5.4
  - bwa=0.7.19
  - bwa-mem2=2.3
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - coreutils=8.25
  - curl=7.87.0
  - dbus=1.16.2
  - ensembl-vep=91.3
  - expat=2.7.3
  - fastp=0.23.4
  - fastqc=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gatk4=4.3.0.0
  - gdk-pixbuf=2.42.10
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - glib=2.84.4
  - glib-tools=2.84.4
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=10.2.0
  - hisat2=2.2.1
  - htslib=1.6
  - icu=73.1
  - isa-l=2.30.0
  - jpeg=9e
  - k8=1.2
  - kernel-headers_linux-64=4.18.0
  - keyutils=1.6.3
  - krb5=1.20.1
  - lcms2=2.15
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libboost=1.82.0
  - libcurl=7.87.0
  - libdb=6.1.26
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libglib=2.84.4
  - libgomp=15.2.0
  - libiconv=1.16
  - libltdl=2.4.3a
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libpng=1.6.50
  - librsvg=2.54.4
  - libsqlite=3.51.1
  - libssh2=1.10.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.5.1
  - libtool=2.5.4
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - minimap2=2.30
  - mysql-common=8.0.32
  - mysql-connector-c=6.1.6
  - mysql-libs=8.0.32
  - mysqlclient=2.1.1
  - ncurses=6.5
  - nextflow=24.10.6
  - nspr=4.38
  - nss=3.118
  - openjdk=11.0.1
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - pango=1.50.7
  - pcre2=10.46
  - perl=5.22.0.1
  - perl-aceperl=1.92
  - perl-algorithm-munkres=0.08
  - perl-app-cpanminus=1.7043
  - perl-appconfig=1.71
  - perl-array-compare=2.11
  - perl-bio-asn1-entrezgene=1.72
  - perl-bio-db-hts=2.7
  - perl-bio-featureio=1.6.905
  - perl-bio-phylo=0.58
  - perl-bio-samtools=1.43
  - perl-bioperl=1.6.924
  - perl-bioperl-core=1.6.924
  - perl-bioperl-run=1.006900
  - perl-capture-tiny=0.36
  - perl-cgi=4.22
  - perl-class-inspector=1.28
  - perl-class-method-modifiers=2.11
  - perl-clone=0.38
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.069
  - perl-compress-raw-zlib=2.069
  - perl-convert-binary-c=0.78
  - perl-convert-binhex=1.125
  - perl-crypt-rc4=2.02
  - perl-data-stag=0.14
  - perl-db-file=1.835
  - perl-dbd-mysql=4.033
  - perl-dbd-sqlite=1.50
  - perl-dbi=1.641
  - perl-devel-globaldestruction=0.13
  - perl-digest-hmac=1.03
  - perl-digest-perl-md5=1.9
  - perl-email-date-format=1.005
  - perl-encode-locale=1.05
  - perl-error=0.17024
  - perl-exporter-tiny=0.042
  - perl-extutils-cppguess=0.12
  - perl-file-listing=6.04
  - perl-file-slurp-tiny=0.004
  - perl-file-sort=1.01
  - perl-file-which=1.20
  - perl-font-afm=1.20
  - perl-gd=2.56
  - perl-graph=0.9704
  - perl-graphviz=2.20
  - perl-html-element-extended=1.18
  - perl-html-entities-numbered=0.04
  - perl-html-formatter=2.14
  - perl-html-parser=3.72
  - perl-html-tableextract=2.13
  - perl-html-tagset=3.20
  - perl-html-tidy=1.56
  - perl-html-tree=5.03
  - perl-html-treebuilder-xpath=0.14
  - perl-http-cookies=6.01
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.11
  - perl-http-negotiate=6.01
  - perl-image-info=1.38
  - perl-image-size=3.300
  - perl-io-compress=2.069
  - perl-io-html=1.001
  - perl-io-sessiondata=1.03
  - perl-io-socket-ssl=2.024
  - perl-io-string=1.08
  - perl-io-stringy=2.111
  - perl-io-tty=1.12
  - perl-ipc-run=0.94
  - perl-jcode=2.07
  - perl-json=2.90
  - perl-json-xs=2.34
  - perl-libwww-perl=6.15
  - perl-libxml-perl=0.08
  - perl-list-moreutils=0.428
  - perl-lwp-mediatypes=6.02
  - perl-lwp-protocol-https=6.06
  - perl-lwp-simple=6.15
  - perl-mailtools=2.14
  - perl-math-cdf=0.1
  - perl-math-derivative=0.04
  - perl-math-random=0.72
  - perl-math-spline=0.02
  - perl-mime-lite=3.030
  - perl-mime-tools=5.507
  - perl-mime-types=2.12
  - perl-mldbm=2.05
  - perl-module-runtime=0.014
  - perl-moo=2.001000
  - perl-net-http=6.09
  - perl-net-ssleay=1.74
  - perl-ntlm=1.09
  - perl-ole-storage_lite=0.19
  - perl-parse-recdescent=1.967013
  - perl-pdf-api2=2.025
  - perl-perlio-gzip=0.19
  - perl-postscript=0.06
  - perl-role-tiny=2.000001
  - perl-scalar-list-utils=1.45
  - perl-sereal=3.015
  - perl-sereal-decoder=3.015
  - perl-sereal-encoder=3.015
  - perl-set-intervaltree=0.11
  - perl-set-scalar=1.29
  - perl-soap-lite=1.19
  - perl-sort-naturally=1.03
  - perl-spreadsheet-parseexcel=0.65
  - perl-spreadsheet-writeexcel=2.40
  - perl-statistics-descriptive=3.0612
  - perl-sub-exporter-progressive=0.001011
  - perl-svg=2.64
  - perl-svg-graph=0.02
  - perl-task-weaken=1.04
  - perl-template-toolkit=2.26
  - perl-test-leaktrace=0.16
  - perl-test-pod=1.51
  - perl-threaded=5.32.1
  - perl-tie-ixhash=1.23
  - perl-timedate=2.30
  - perl-tree-dag_node=1.29
  - perl-type-tiny=1.000005
  - perl-unicode-map=0.112
  - perl-uri=1.71
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.45
  - perl-xml-dom-xpath=0.14
  - perl-xml-filter-buffertext=1.01
  - perl-xml-libxml=2.0124
  - perl-xml-libxslt=1.94
  - perl-xml-namespacesupport=1.11
  - perl-xml-parser=2.44
  - perl-xml-regexp=0.04
  - perl-xml-sax=0.99
  - perl-xml-sax-base=1.08
  - perl-xml-sax-expat=0.51
  - perl-xml-sax-writer=0.56
  - perl-xml-simple=2.22
  - perl-xml-twig=3.49
  - perl-xml-writer=0.625
  - perl-xml-xpath=1.33
  - perl-xml-xpathengine=0.14
  - perl-yaml=1.24
  - pip=25.3
  - pixman=0.46.4
  - poppler=22.12.0
  - poppler-data=0.4.12
  - pthread-stubs=0.3
  - python=3.11.5
  - python_abi=3.11
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - star=2.7.10b
  - sysroot_linux-64=2.28
  - tidyp=1.04
  - tk=8.6.15
  - trimmomatic=0.40
  - tzdata=2025b
  - ucsc-bedgraphtobigwig=357
  - ucsc-bigwigtobedgraph=357
  - unzip=6.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - cutadapt==5.2
      - dnaio==1.2.4
      - isal==1.8.0
      - xopen==2.0.2
      - zlib-ng==1.0.0
prefix: /home/snehal/miniconda3/envs/bnf
